name: Lock Threads
permissions:
  issues: write
  pull-requests: write
jobs:
  action:
    if: github.repository_owner == 'psf'
    runs-on: self-hosted
    steps:
    - uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7
      with:
        issue-lock-inactive-days: 90
        pr-lock-inactive-days: 90
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  schedule:
  - cron: 0 0 * * *
