name: "GitHub Actions Security Analysis with zizmor \U0001F308"
permissions: {}
jobs:
  zizmor:
    runs-on: self-hosted
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: false
    - name: "Run zizmor \U0001F308"
      uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - '**'
